### ISSUE TITLE
Macでのインストール時のエラー(Visusal Studio Code の設定が必要)

### ISSUE THREAD

**Issue by khachiman** [ETrobocon/etrobo#11]
インストール時に以下のエラーが起きました。

![hachiman_—_Start_ETrobo_command_—_80×24_と_robots-6th](https://user-images.githubusercontent.com/13989002/84988037-3e72e680-b17c-11ea-9386-d7eb8bf46c0c.png)

「code」はVlisual Studio Codeを起動していますが、Visual Studio Codeで事前に設定しないと、/usr/local/bin/code はインストールされないようです。

以下を参考にVisual Studio Codeを設定することにより、無事 make sample まで実行を確認できました。
https://qiita.com/naru0504/items/c2ed8869ffbf7682cf5c

**Comment by jtFuruhata** [comment]
ご報告ありがとうございます、ご指摘の件まったくその通りで、「etroboパッケージインストール前の動作環境構築手順（macOS）」の通りに行わなければいけません。
https://github.com/ETrobocon/etrobo/wiki/sim_mac
判り辛くてすみません、ドキュメントの方は鋭意整備中でして、もう少し判りやすく記述するようにいたします、もう少々お時間をください。

**Comment by khachiman** [comment]
すみません。ちゃんと書いてあったのですね。
そこを読んだはずだったのですが、後半を読んでいなかったようです。; ;

**Comment by jtFuruhata** [comment]
余計なことは書いてあるのに肝心のところが読まれないのはダメドキュメントですよね^^;　Macに関してはスクショ入りのステップバイステップを用意中です。

**Comment by jtFuruhata** [comment]
あっ、それよりもログの上の方でranlibコケ気味なのが気になります、`make sample`で正しく実行されてますでしょうか？

って、あ、うちでも出てました、大丈夫です^^;

**Comment by khachiman** [comment]
`make sample`でコンパイルは無事終了し、シミュレータ上で元気に動いています。

**Comment by jtFuruhata** [comment]
お騒がせしました^^; サンプルコースでも一通り試せると思いますので、楽しんでください
