### ISSUE TITLE
インストーラーがダウンロードに失敗する

### ISSUE THREAD

**Issue by jtFuruhata** [ETrobocon/etrobo#12]
現在、この問題の原因を探るため、ダウンロードに失敗した場合はもれなくインストーラーを停止するようにしてあります。
インストーラーが停止した場合は、その時のログをこちらでご報告いただければ幸いです。エラーの出たダウンロードに関する部分だけで結構です、知りたいのはファイル名とエラーメッセージになります。

**Comment by kuboaki** [comment]
久保秋です。
Macです。
一応、最後まで行ってそうですが、VSCodeの立ち上げには至らなかったのでlogあげておきます。

[kuboaki_log01.txt](https://github.com/ETrobocon/etrobo/files/4816345/kuboaki_log01.txt)

**Comment by jtFuruhata** [comment]
ダウンロード失敗ログだけでOKです、VSCode立ち上げは #11 でお願いします～

**Comment by jtFuruhata** [comment]
プロキシの問題は #19 に集約し、クローズします。
