### ISSUE TITLE
etroboパッケージのインストールが出来ません 

### ISSUE THREAD

**Issue by Naoyamagucih** [ETrobocon/etrobo#21]
環境はWindows10です。　etroboパッケージインストール前の動作環境構築手順は完了しています。

コマンドプロンプトにコマンドをコピー&ペーストし実行すると、Start ETrobo.cmdは作成されるのですが、
 その後ダブルクリックしてもインストールを開始どころか反応がありません。

何卒お力添えのほど宜しくお願い致します。

**Comment by jtFuruhata** [comment]
HTTPプロキシの内側からインストールしていないでしょうか？
もしもそうでしたら、現在この対策アップデートを作成中です。
もちろん、Ubuntuで適切にプロキシの設定が行われていれば問題は発生しません。

**Comment by Naoyamagucih** [comment]
仰る通り、プロキシの設定をしていませんでした。

プロキシを設定後再度実行すると、
インストールを開始しましたが
fatal: unable to access 'https://github.com/ETrobocon/etrobo.git/': Failed to connect to github.com port 443: Connection refused
のエラーが出ました。

**Comment by jtFuruhata** [comment]
```
git config --global http.proxy HTTPプロキシ設定URL
git config --global https.proxy HTTPプロキシ設定URL
```

を試してみてください。 `HTTPプロキシ設定URL` は `http_proxy` 環境変数と同じものを指定します。

**Comment by Naoyamagucih** [comment]
etroboパッケージがインストールできました。
ありがとうございます。

**Comment by jtFuruhata** [comment]
よかったです、実装も急ぎます…
