### ISSUE TITLE
EV3RT_SDK_LIB_DIR経路を見つけ出せないです。

### ISSUE THREAD

**Issue by Robotics-Ro** [ETrobocon/etrobo#22]
・環境設定無事完了
・Windows10

去年、実機で動いたプログラムを試している中ですが色々難航を迎えています。
EV3RT_SDK_LIB_DIRの方が読められなくてev3api.hなどのヘッダファイルがIncludeできないみたいです。
<img width="1280" alt="error" src="https://user-images.githubusercontent.com/54663239/87848612-df3ff780-c91c-11ea-8e3e-e7f17bc66cd6.png">
<img width="1280" alt="problem" src="https://user-images.githubusercontent.com/54663239/87848613-e0712480-c91c-11ea-8756-ae891d5f8f72.png">

wslのterminalで
printenvしても経路が出ないです。

**Comment by jtFuruhata** [comment]
検証はしていませんが、事実であったとしてもetrobo環境ではなくEV3RT側の問題です。
