### ISSUE TITLE
HackEVの実機にモジュールのビルドと転送が出来ません

### ISSUE THREAD

**Issue by Naoyamagucih** [ETrobocon/etrobo#27]
マイクロSDカードがPC上で検知できません

インテリジェントブロックにマイクロSDカードを挿入しただけではUSBポートに接続しても検知できないんですか？

**Comment by jtFuruhata** [comment]
[こちら](https://github.com/ETrobocon/etrobo#%E5%8B%95%E4%BD%9C%E7%A2%BA%E8%AA%8D%E4%B8%BB%E3%81%AA%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%81%AE%E8%AA%AC%E6%98%8E)をご覧ください。

**Comment by Naoyamagucih** [comment]
カードリーダーを使用し、マイクロSDカードに直接ブートイメージを保存することで解決しました。
