### ISSUE TITLE
ビルド環境について教えてください

### ISSUE THREAD

**Issue by tkm-yoshida** [ETrobocon/etrobo#28]
ETroboconの中にシミュレーション環境とビルド環境はインストールできたのですが、
ビルド環境だけがあるフォルダ(もしくはファイル)の場所を教えてもらうことは可能でしょうか?

**Comment by jtFuruhata** [comment]
標準インストールの場合：
- Windows ... **WSL上の** `/home/<UserID>/etrobo`
- Mac ... `/Users/<UserID>/BeerHall/etrobo`
- Linux ... `/home/<UserID>/etrobo`
- ChromeOS ... **Linux(ベータ版)上の** `/home/<UserID>/etrobo`

**Comment by tkm-yoshida** [comment]
ありがとうございます
