### ISSUE TITLE
プログラムが正常に動作しない

### ISSUE THREAD

**Issue by inazuma04157** [ETrobocon/etrobo#31]
"要素技術とモデルを開発に使おう: コードとモデル図を対応づけてみよう"のsample00を作成し
シミュレーター上で実行したのですがすぐに止まってしまいます。
＜作業環境＞
windows10

止まった時にはこの文が同時に出ます
[ l_app runner: exit: Athrill2 was shutted down ]
[ l_app runner: duration of running: 8 secs in real-world time ]
[ athrill_runner #19712: terminated. ]
[ asp launcher #19671: terminated. ]

**Comment by jtFuruhata** [comment]
上記メッセージは正常終了の場合でも出ます。その他の部分のログもいただけますか？
（ユーザ名など機微情報は黒塗りで結構です）

**Comment by inazuma04157** [comment]
こちらで問題ないでしょうか

invoker make app=sample00 sim up
rm -rf /home/ユーザー名/etrobo/hrp3/sdk/workspace/.././OBJ/
/usr/lib/ruby/2.5.0/shell.rb:147: warning: Insecure world writable dir /mnt/c/app/taten/product/11.1.0 in PATH, mode 040777
Generating Makefile from ../common/Makefile.app.
make[1]: Entering directory '/home/ユーザー名/etrobo/hrp3/sdk/OBJ'
rm -f cfg1_out cfg1_out.o cfg1_out.c cfg1_out.syms cfg1_out.srec module_cfg.h module_cfg.c \#* *~ *.o
make[1]: Leaving directory '/home/ユーザー名/etrobo/hrp3/sdk/OBJ'
make[1]: Entering directory '/home/ユーザー名/etrobo/hrp3/sdk/OBJ'
  CFG[1]  module_cfg.h
[cfg.rb] Generated cfg1_out.c
  CFG[2]  module_cfg.h
[cfg.rb] Generated module_cfg.c
[cfg.rb] Generated module_cfg.h
make[1]: Leaving directory '/home/ユーザー名/etrobo/hrp3/sdk/OBJ'
make[1]: Entering directory '/home/ユーザー名/etrobo/hrp3/sdk/OBJ'
  CC      module_cfg.c
  CC      ../../library/t_perror.c
  CC      ../../library/strerror.c
  CC      ../../library/vasyslog.c
  CC      ../../target/ev3_gcc/TLSF-2.4.6/src/tlsf.c
  CC      ../common/ev3api/src/ev3api.c
  CC      ../common/ev3api/src/ev3api_battery.c
  CC      ../common/ev3api/src/ev3api_brick.c
  CC      ../common/ev3api/src/ev3api_fs.c
  CC      ../common/ev3api/src/ev3api_speaker.c
  CC      ../common/ev3api/src/ev3api_lcd.c
  CC      ../common/ev3api/src/ev3api_motor.c
  CC      ../common/ev3api/src/ev3api_newlib.c
  CC      ../common/ev3api/src/ev3api_sensor.c
  CXX     ../workspace/sample00/util.cpp
  CXX     ../workspace/sample00/app.cpp
  LD      app
make[1]: Leaving directory '/home/ユーザー名/etrobo/hrp3/sdk/OBJ'
fakemake on HRP3: build succeed: sample00
rm -rf /home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/workspace/.././OBJ/
cd /home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/workspace/.././OBJ/ && \
ruby /home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/workspace/../../configure.rb  -T v850_gcc -A app \
        -a ../workspace/sample00 \
        -D ../.. \
        -l c++ \
        -m ../common/Makefile.img \
        -o "" \
        -t \
        -d ./dep \
        -C ../common/athrill_common.cdl \
        -U "" && \
make clean
/usr/lib/ruby/2.5.0/shell.rb:147: warning: Insecure world writable dir /mnt/c/app/taten/product/11.1.0 in PATH, mode 040777
Generating Makefile from ../common/Makefile.img.
make[1]: Entering directory '/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ'
rm -f \#* *~ ./*.o ./dep/*.d  check.timestamp
rm -f asp asp.syms asp.srec asp.bin
rm -f kernel_opt.timestamp   cfg3_out.db
rm -f cfg3_out.syms cfg3_out.srec 
rm -f kernel_cfg.timestamp kernel_cfg.h kernel_cfg.c   cfg2_out.db
rm -f cfg2_out.syms cfg2_out.srec kernel_cfg_asm.S 
rm -f offset.timestamp offset.h
rm -f cfg1_out.syms cfg1_out.srec cfg1_out
rm -f cfg1_out.timestamp cfg1_out.c cfg1_out.db
rm -rf ./gen
rm -f libkernel.a
make[1]: Leaving directory '/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ'
_# -S "banner.o syslog.o serial.o logtask.o" 
(cd /home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/workspace/.././OBJ/ && \
make offset.h kernel_cfg.h && \
make -j8 > /dev/null ) && \
cp /home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/workspace/.././OBJ//asp /home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/workspace && \
echo "/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/workspace/sample00" > /home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/workspace/appdir
make[1]: Entering directory '/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ'
if grep -sq  "tecsgen.cfg" ../workspace/sample00/app.cfg ; then \
        cat ../workspace/sample00/app.cfg > tmp_app.cfg ; \
else \
        echo "INCLUDE(\"tecsgen.cfg\")" >> tmp_app.cfg; \
        cat ../workspace/sample00/app.cfg >> tmp_app.cfg ; \
fi; 
ruby ../../tecsgen/tecsgen.rb ../common/athrill_common.cdl -R -I. -I../../include -I. -I../../include -I../../target/v850_gcc/drivers -I../../target/v850_gcc -I../../arch/v850_gcc -I../../arch/gcc -I../.. -I../.. -I/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ/../../../athrill/apl/include -I../common/ev3api/include -I../common/ev3api/src -I../workspace/sample00 -I../../target/v850_gcc/athrill -I../../../athrill/apl/include -I../../../athrill/apl/src -I../common -I../common/ev3api -I../common/ev3api/include -I../../../athrill/apl/include -I../common/library/libcpp-ev3/include -I./gen -I../../tecs_kernel -I/tecs -I/tecs/rpc -I../../target/v850_gcc/drivers/brick/include -I../../target/v850_gcc/drivers/common/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/arch/arm/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/include -I../../target/v850_gcc/drivers/gpio/include -I../../target/v850_gcc/drivers/motor/include -I../../target/v850_gcc/drivers/uart/include -I../../target/v850_gcc/pil/include -I../../target/v850_gcc/platform/include -I../../target/v850_gcc/TLSF-2.4.6/include --cpp "v850-elf-gcc -DBUILD_EV3_PLATFORM -DLABEL_ASM  -DTOPPERS_SUPPORT_PROTECT -I. -I../../include -I. -I../../include -I../../target/v850_gcc/drivers -I../../target/v850_gcc -I../../arch/v850_gcc -I../../arch/gcc -I../.. -I../.. -I/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ/../../../athrill/apl/include -I../common/ev3api/include -I../common/ev3api/src -I../workspace/sample00 -I../../target/v850_gcc/athrill -I../../../athrill/apl/include -I../../../athrill/apl/src -I../common -I../common/ev3api -I../common/ev3api/include -I../../../athrill/apl/include -I../common/library/libcpp-ev3/include -I./gen -I../../tecs_kernel -I/tecs -I/tecs/rpc -I../../target/v850_gcc/drivers/brick/include -I../../target/v850_gcc/drivers/common/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/arch/arm/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/include -I../../target/v850_gcc/drivers/gpio/include -I../../target/v850_gcc/drivers/motor/include -I../../target/v850_gcc/drivers/uart/include -I../../target/v850_gcc/pil/include -I../../target/v850_gcc/platform/include -I../../target/v850_gcc/TLSF-2.4.6/include  -D TECSGEN -E" -g ./gen
tecsgen  version 1.5.0  Copyright(c) 2008-2017, TOPPERS project. All rights reserved.
/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/tecsgen/tecslib/core/componentobj.rb:7325: warning: Insecure world writable dir /mnt/c/app/taten/product/11.1.0 in PATH, mode 040777
  CFG[1]  cfg1_out.timestamp
ruby ../../cfg/cfg.rb --pass 1 --kernel asp -I. -I../../include -I. -I../../include -I../../target/v850_gcc/drivers -I../../target/v850_gcc -I../../arch/v850_gcc -I../../arch/gcc -I../.. -I../.. -I/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ/../../../athrill/apl/include -I../common/ev3api/include -I../common/ev3api/src -I../workspace/sample00 -I../../target/v850_gcc/athrill -I../../../athrill/apl/include -I../../../athrill/apl/src -I../common -I../common/ev3api -I../common/ev3api/include -I../../../athrill/apl/include -I../common/library/libcpp-ev3/include -I./gen -I../../tecs_kernel -I/tecs -I/tecs/rpc -I../../target/v850_gcc/drivers/brick/include -I../../target/v850_gcc/drivers/common/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/arch/arm/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/include -I../../target/v850_gcc/drivers/gpio/include -I../../target/v850_gcc/drivers/motor/include -I../../target/v850_gcc/drivers/uart/include -I../../target/v850_gcc/pil/include -I../../target/v850_gcc/platform/include -I../../target/v850_gcc/TLSF-2.4.6/include --api-table ../../kernel/kernel_api.def --symval-table ../../kernel/kernel_sym.def  --symval-table ../../target/v850_gcc/target_sym.def --api-table ../common/ev3api/ev3api.csv \
                                        -M ./dep/cfg1_out_c.d ../../target/v850_gcc/target_kernel.cfg tmp_app.cfg
tmp_app.cfg:6: warning: `DOMAIN' is not supported
[cfg.rb] Generated cfg1_out.c
v850-elf-gcc -c -O2 -Wall -g   -mv850e2v3 -mdisable-callt -mhard-float -DMAKE_SIM -DBUILD_EV3_PLATFORM -DLABEL_ASM  -DTOPPERS_SUPPORT_PROTECT -I. -I../../include -I. -I../../include -I../../target/v850_gcc/drivers -I../../target/v850_gcc -I../../arch/v850_gcc -I../../arch/gcc -I../.. -I../.. -I/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ/../../../athrill/apl/include -I../common/ev3api/include -I../common/ev3api/src -I../workspace/sample00 -I../../target/v850_gcc/athrill -I../../../athrill/apl/include -I../../../athrill/apl/src -I../common -I../common/ev3api -I../common/ev3api/include -I../../../athrill/apl/include -I../common/library/libcpp-ev3/include -I./gen -I../../tecs_kernel -I/tecs -I/tecs/rpc -I../../target/v850_gcc/drivers/brick/include -I../../target/v850_gcc/drivers/common/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/arch/arm/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/include -I../../target/v850_gcc/drivers/gpio/include -I../../target/v850_gcc/drivers/motor/include -I../../target/v850_gcc/drivers/uart/include -I../../target/v850_gcc/pil/include -I../../target/v850_gcc/platform/include -I../../target/v850_gcc/TLSF-2.4.6/include -DALLFUNC  -I../../kernel ../../arch/v850_gcc/start.S
v850-elf-gcc -c -O2 -Wall -g   -mv850e2v3 -mdisable-callt -mhard-float -DMAKE_SIM -DBUILD_EV3_PLATFORM -DLABEL_ASM  -DTOPPERS_SUPPORT_PROTECT -I. -I../../include -I. -I../../include -I../../target/v850_gcc/drivers -I../../target/v850_gcc -I../../arch/v850_gcc -I../../arch/gcc -I../.. -I../.. -I/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ/../../../athrill/apl/include -I../common/ev3api/include -I../common/ev3api/src -I../workspace/sample00 -I../../target/v850_gcc/athrill -I../../../athrill/apl/include -I../../../athrill/apl/src -I../common -I../common/ev3api -I../common/ev3api/include -I../../../athrill/apl/include -I../common/library/libcpp-ev3/include -I./gen -I../../tecs_kernel -I/tecs -I/tecs/rpc -I../../target/v850_gcc/drivers/brick/include -I../../target/v850_gcc/drivers/common/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/arch/arm/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/include -I../../target/v850_gcc/drivers/gpio/include -I../../target/v850_gcc/drivers/motor/include -I../../target/v850_gcc/drivers/uart/include -I../../target/v850_gcc/pil/include -I../../target/v850_gcc/platform/include -I../../target/v850_gcc/TLSF-2.4.6/include -DALLFUNC  -I../../kernel ../../arch/v850_gcc/v850_mul.S
  CC      cfg1_out.c
  LINK    cfg1_out
v850-elf-g++ -O2 -Wall -g   -mv850e2v3 -mdisable-callt -mhard-float -DMAKE_SIM -DBUILD_EV3_PLATFORM -DLABEL_ASM  -DTOPPERS_SUPPORT_PROTECT -I. -I../../include -I. -I../../include -I../../target/v850_gcc/drivers -I../../target/v850_gcc -I../../arch/v850_gcc -I../../arch/gcc -I../.. -I../.. -I/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ/../../../athrill/apl/include -I../common/ev3api/include -I../common/ev3api/src -I../workspace/sample00 -I../../target/v850_gcc/athrill -I../../../athrill/apl/include -I../../../athrill/apl/src -I../common -I../common/ev3api -I../common/ev3api/include -I../../../athrill/apl/include -I../common/library/libcpp-ev3/include -I./gen -I../../tecs_kernel -I/tecs -I/tecs/rpc -I../../target/v850_gcc/drivers/brick/include -I../../target/v850_gcc/drivers/common/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/arch/arm/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/include -I../../target/v850_gcc/drivers/gpio/include -I../../target/v850_gcc/drivers/motor/include -I../../target/v850_gcc/drivers/uart/include -I../../target/v850_gcc/pil/include -I../../target/v850_gcc/platform/include -I../../target/v850_gcc/TLSF-2.4.6/include -L . -nostdlib -nostartfiles -lgcc -lc    -nostdlib -Wl,-T,../../target/v850_gcc/v850es_fk3.ld -o cfg1_out \
                                        start.o v850_mul.o  ./cfg1_out.o  -lstdc++ -lm -lc -lgcc -std=c++11  
  NM      cfg1_out.syms
  OBJCOPY cfg1_out.srec
  CFG[2]  offset.timestamp
ruby ../../cfg/cfg.rb --pass 2 -O --kernel asp -I. -I../../include -I. -I../../include -I../../target/v850_gcc/drivers -I../../target/v850_gcc -I../../arch/v850_gcc -I../../arch/gcc -I../.. -I../.. -I/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ/../../../athrill/apl/include -I../common/ev3api/include -I../common/ev3api/src -I../workspace/sample00 -I../../target/v850_gcc/athrill -I../../../athrill/apl/include -I../../../athrill/apl/src -I../common -I../common/ev3api -I../common/ev3api/include -I../../../athrill/apl/include -I../common/library/libcpp-ev3/include -I./gen -I../../tecs_kernel -I/tecs -I/tecs/rpc -I../../target/v850_gcc/drivers/brick/include -I../../target/v850_gcc/drivers/common/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/arch/arm/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/include -I../../target/v850_gcc/drivers/gpio/include -I../../target/v850_gcc/drivers/motor/include -I../../target/v850_gcc/drivers/uart/include -I../../target/v850_gcc/pil/include -I../../target/v850_gcc/platform/include -I../../target/v850_gcc/TLSF-2.4.6/include -T ../../target/v850_gcc/target_offset.trb \
                        --rom-symbol cfg1_out.syms --rom-image cfg1_out.srec
[cfg.rb] Generated offset.h
  CFG[2]  kernel_cfg.timestamp
ruby ../../cfg/cfg.rb --pass 2 --kernel asp -I. -I../../include -I. -I../../include -I../../target/v850_gcc/drivers -I../../target/v850_gcc -I../../arch/v850_gcc -I../../arch/gcc -I../.. -I../.. -I/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ/../../../athrill/apl/include -I../common/ev3api/include -I../common/ev3api/src -I../workspace/sample00 -I../../target/v850_gcc/athrill -I../../../athrill/apl/include -I../../../athrill/apl/src -I../common -I../common/ev3api -I../common/ev3api/include -I../../../athrill/apl/include -I../common/library/libcpp-ev3/include -I./gen -I../../tecs_kernel -I/tecs -I/tecs/rpc -I../../target/v850_gcc/drivers/brick/include -I../../target/v850_gcc/drivers/common/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/arch/arm/include -I../../target/v850_gcc/drivers/common/virtual-linux-kernel/include -I../../target/v850_gcc/drivers/gpio/include -I../../target/v850_gcc/drivers/motor/include -I../../target/v850_gcc/drivers/uart/include -I../../target/v850_gcc/pil/include -I../../target/v850_gcc/platform/include -I../../target/v850_gcc/TLSF-2.4.6/include -T ../../target/v850_gcc/target_kernel.trb
[cfg.rb] Generated kernel_cfg.h
[cfg.rb] Generated kernel_cfg.c
[cfg.rb] Generated kernel_cfg_asm.S
make[1]: Leaving directory '/home/ユーザー名/etrobo/ev3rt-athrill-v850e2m/sdk/OBJ'
  CC      ../../target/v850_gcc/platform/src/ev3main.c
  CC      ../../target/v850_gcc/pil/src/ev3_svc.c
  CC      ../../target/v850_gcc/pil/src/driver_interface_brick.c
  CC      ../../target/v850_gcc/drivers/brick/src/brick_dri.c
  CC      ../../target/v850_gcc/drivers/uart/src/uart_dri.c
  CC      ../../target/v850_gcc/drivers/motor/src/motor_dri.c
  CC      ../../target/v850_gcc/drivers/gpio/src/gpio_dri.c
  CC      ../../library/log_output.c
  CC      ../../library/vasyslog.c
  CC      ../../library/t_perror.c
  CC      ../../library/strerror.c
  CC      ../common/ev3api/src/ev3api.c
  CC      ../common/ev3api/src/ev3api_battery.c
  CC      ../common/ev3api/src/ev3api_brick.c
  CC      ../common/ev3api/src/ev3api_fs.c
  CC      ../common/ev3api/src/ev3api_speaker.c
  CC      ../common/ev3api/src/ev3api_lcd.c
  CC      ../common/ev3api/src/ev3api_motor.c
  CC      ../common/ev3api/src/ev3api_newlib.c
  CC      ../common/ev3api/src/ev3api_sensor.c
../../syssvc/tSerialAdapter.c: In function 'serial_opn_por':
../../syssvc/tSerialAdapter.c:67:7: warning: unused variable 'fd' [-Wunused-variable]
   int fd = port_table[portid] = filesys_serial_open(portid);
       ^
  CC      kernel_cfg_asm.S
  CC      kernel_cfg.c
  CC[K]   ../../arch/v850_gcc/prc_support.S
  CC[K]   ../../arch/v850_gcc/prc_sil.S
  CC[K]   ../../target/v850_gcc/target_config.c
  CC[K]   ../../target/v850_gcc/TLSF-2.4.6/src/tlsf.c
  CC[K]   ../../../athrill/apl/src/athrill-syscall.c
  CC[K]   ../../arch/v850_gcc/prc_config.c
  CC[K]   ../../arch/v850_gcc/chip_timer.c
  CC[K]   ../../kernel/startup.c
../../target/v850_gcc/target_config.c:15:13: warning: 'target_fput_initialize' declared 'static' but never defined [-Wunused-function]
 static void target_fput_initialize(void);
             ^
../../target/v850_gcc/target_config.c: In function '_kernel_target_exit':
../../target/v850_gcc/target_config.c:56:1: warning: 'noreturn' function does return
 }
 ^
  CC[K]   ../../kernel/task.c
  CC[K]   ../../kernel/taskhook.c
  CC[K]   ../../kernel/wait.c
  CC[K]   ../../kernel/time_event.c
  CC[K]   ../../kernel/task_manage.c
  CC[K]   ../../kernel/task_refer.c
  CC[K]   ../../kernel/task_sync.c
../../kernel/time_event.c: In function '_kernel_set_hrt_event':
../../kernel/time_event.c:409:3: warning: this decimal constant is unsigned only in ISO C90
   target_hrt_set_event(HRTCNT_BOUND);   /*［ASPD1007］*/
   ^
../../kernel/time_event.c:416:3: warning: this decimal constant is unsigned only in ISO C90
   if (hrtcnt > HRTCNT_BOUND) {
   ^
../../kernel/time_event.c:417:4: warning: this decimal constant is unsigned only in ISO C90
    target_hrt_set_event(HRTCNT_BOUND);  /*［ASPD1006］*/
    ^
  CC[K]   ../../kernel/task_term.c
  CC[K]   ../../kernel/semaphore.c
  CC[K]   ../../kernel/eventflag.c
  CC[K]   ../../kernel/dataqueue.c
  CC[K]   ../../kernel/pridataq.c
  CC[K]   ../../kernel/mutex.c
  CC[K]   ../../kernel/mempfix.c
  CC[K]   ../../kernel/time_manage.c
  CC[K]   ../../kernel/cyclic.c
  CC[K]   ../../kernel/alarm.c
  CC[K]   ../../kernel/sys_manage.c
  CC[K]   ../../kernel/interrupt.c
  CC[K]   ../../kernel/exception.c
../../kernel/interrupt.c: In function '_kernel_initialize_interrupt':
../../kernel/interrupt.c:406:17: warning: variable 'p_inhinib' set but not used [-Wunused-but-set-variable]
  const INHINIB *p_inhinib;
                 ^
/home/ユーザー名/etrobo/athrill-gcc-package/usr/local/athrill-gcc/v850-elf/include/stdlib.h: In function 'exit':
../../target/v850_gcc/athrill/athrill-libgcc.c:43:1: warning: 'noreturn' function does return
 }
 ^
  RM      libkernel.a
  AR      libkernel.a
  RANLIB  libkernel.a
fakemake on ASP3: build succeed: sample00.asp
launch sim
[ asp launcher #859: launch sample00.asp as l_app by runner #900 ]
[ athrill_runner #900: Athrill VM is running on #932 ]
core id num=1
ROM : START=0x0 SIZE=512
RAM : START=0x200000 SIZE=512
RAM : START=0x5ff7000 SIZE=10240
RAM : START=0x7ff7000 SIZE=10240
ELF SET CACHE RIGION:addr=0x0 size=145 [KB]
Elf loading was succeeded:0x0 - 0x2465c : 145.604 KB
Elf loading was succeeded:0x2465c - 0x24b8c : 1.304 KB
ELF SYMBOL SECTION LOADED:index=93
ELF SYMBOL SECTION LOADED:sym_num=1374
ELF STRING TABLE SECTION LOADED:index=94
DEBUG_FUNC_VDEV_TX_IPADDR = 127.0.0.1
VDEV:TX IPADDR=127.0.0.1
VDEV:TX PORTNO=54001
VDEV:RX IPADDR=127.0.0.1
VDEV:RX PORTNO=54002
DEVICE_CONFIG_COMPLEMENTAL_TX_SENDING=1
DEVICE_CONFIG_RESET_AREA_OFFSET=68
DEVICE_CONFIG_RESET_AREA_SIZE=20
DEBUG_FUNC_FT_LOG_SIZE=1024
athrill_device_func_call=0x200524

TOPPERS/ASP3 Kernel Release 3.2.0 for V850-ESFK3 (Nov 13 2020, 11:40:22)
Copyright (C) 2000-2003 by Embedded and Real-Time Systems Laboratory
                            Toyohashi Univ. of Technology, JAPAN
Copyright (C) 2004-2017 by Embedded and Real-Time Systems Laboratory
            Graduate School of Information Science, Nagoya Univ., JAPAN

brick_dri initialized.
   _____   ______ ___  ______
  / __/ | / /_  // _ \/_  __/
 / _/ | |/ //_ </ , _/ / /
/___/ |___/____/_/|_| /_/
 
====================>Beta 7<=

**Comment by jtFuruhata** [comment]
惜しい…その続きが…みたい…です…
EV3RTの起動を確認したメッセージが出ていると思うのですが。

**Comment by inazuma04157** [comment]
返信遅れてしまってすいません、こちらで問題ないでしょうか

Powered by TOPPERS/ASP3 RTOS of Hakoniwa
Initialization is completed..
System logging task is started.
[ l_app runner: V850E2M VCPU is powered on ]
[ l_app runner: Athrill2 is booted up ]
[ launcher: CONTROLLABLE detected ]

*** WARNING ***

You are *NOT* using the 'etrobosim2020_4.0' which is a simulator for competition.
If you are a participant, run 'update sim' to download it.

[ l_app runner: EV3RT is booted up ]
[ l_app runner: EV3RT boot time: 7 secs. ]

[ l_app runner: exit: Athrill2 was shutted down ]
[ l_app runner: duration of running: 10 secs in real-world time ]
[ athrill_runner #855: terminated. ]
[ asp launcher #811: terminated. ]

**Comment by jtFuruhata** [comment]
なるほど、これはWARNINGメッセージの通りです、文面を拝見したところETロボコンに参加されている方の様ですので、指示に従ってシミュレータをダウンロードしてインストールしてください。

**Comment by inazuma04157** [comment]
update simを実行したところユーザーネームとパスワードを要求されましたが何を入力すればいいのでしょうか？

**Comment by jtFuruhata** [comment]
ETロボコン参加者に割り当てられているサイボウズのアカウントです。

**Comment by inazuma04157** [comment]
無事動きました、お手数おかけ致しました
