### ISSUE TITLE
起動後のログインについて

### ISSUE THREAD

**Issue by NAMITO-WaveDoor** [ETrobocon/etrobo#32]
インストール時にログインせず、VisualStdio起動後にログインしたのですが、シミュレータを起動するとサンプルの簡易コースしか選べません。

ログインには「update sim」コマンド入れてからログインしました。認証も成功しています。

ログイン方法は合ってますでしょうか？また他に考えれる原因がありますでしょうか？
よろしくお願いします。

**Comment by jtFuruhata** [comment]
はい、その動作で正しいです。現行の2021年度公開版etrobo環境での2020年度本コースの起動方法に関しては、2020年度参加者コミュニティSlackをご参照ください。
