### ISSUE TITLE
Mac用の環境構築コマンドが失敗する

### ISSUE THREAD

**Issue by ie-Yoshisaur** [ETrobocon/etrobo#39]
[このページ(ETrobocon/etrobo/wiki/etrobo_pkg_install_mac)](https://github.com/ETrobocon/etrobo/wiki/etrobo_pkg_install_mac)に書かれている通りに、以下のコマンドを実行して、`Start ETrobo.command`ファイルをダブルクリックしたところ、

`$ cd Desktop; echo 'name=startetrobo_mac.command; if [ ! -f $name ]; then curl -O https://raw.githubusercontent.com/ETrobocon/etrobo/master/scripts/$name; chmod +x ~/$name; fi; ~/$name' > "Start ETrobo.command"; chmod +x "Start ETrobo.command"
`

---

以下のエラーを出力して失敗しました。

```
line 2: syntax error near unexpected token `newline'
line 2: `<?xml version="1.0" encoding="utf-8"?>'
```

**Comment by jtFuruhata** [comment]
- そのダブルクリックしたファイルがデスクトップに生成されたものであることを確認してください。
- その同じファイルをもう一度ダブルクリックし、開いたターミナルのログを全て貼ってください。
- その同じファイルを右クリック（二本指タップ）して、「このアプリケーションで開く」→「テキストエディット」で中身を開き、その内容を貼ってください。

ETロボコン参加者である場合は、参加者Slackにスクショを貼っていただくのが一番こちらも判断しやすく、マシン名などを不用意に世界中にさらす心配もなく、良いのではないかと思います。
