### ISSUE TITLE
Proxy環境下でgem install shellに失敗する

### ISSUE THREAD

**Issue by juno-nishizaki** [ETrobocon/etrobo#40]
（ログ等なくて申し訳ないです）

Proxy環境下のWindows10 + WSL2 (Ubuntu-20.04)  構成でインストールしたところ、gem install shellのところでインターネットに接続できずにエラーとなりました。

インストーラーの内容を確認したところ、下記の行が誤っているように見えます。
https://github.com/ETrobocon/etrobo/blob/master/scripts/startetrobo#L325

Wikiには、以下のように記述されれており `-E` オプションの指定する位置が違っています。
https://github.com/ETrobocon/etrobo/wiki/sim_win_setup_in_proxy#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0http_proxy%E3%81%AB%E3%83%97%E3%83%AD%E3%82%AD%E3%82%B7%E8%A8%AD%E5%AE%9A%E3%81%8C%E6%B8%88%E3%82%93%E3%81%A7%E3%81%84%E3%82%8B%E5%A0%B4%E5%90%88%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E5%AE%9F%E8%A1%8C%E6%99%82%E3%81%AF%E6%8C%87%E5%AE%9A%E4%B8%8D%E8%A6%81

**Comment by juno-nishizaki** [comment]
補足です。
Wikiに記述されているコマンド `sudo -E gem install shell` を個別に実行したところ正常にインストールできました。

**Comment by jtFuruhata** [comment]
修正しました、ご指摘ありがとうございました。

**Comment by juno-nishizaki** [comment]
迅速なご対応ありがとうございました。修正後のスクリプトで問題なくインストールできました。
