### ISSUE TITLE
シミュレータ使用方法

### ISSUE THREAD

**Issue by acs-tanakachikako** [ETrobocon/etrobo#43]
今更ですがシミュレータ(2023_6.0.1b)を使用したいです。
走行体の初期位置を変更したいのですが、
例えば
sim ctl pos 10 0 -15.5 0
をやっても変わっているようにお見受けしません。
sim show
とすると、initLX～initLROTまで先の値が入っているようなので値としては入ったのではないかと思っています。
どうしたら走行体の位置を変えることができるのでしょうか？

**Comment by jtFuruhata** [comment]
手元の環境では正常に動作しています、まずコマンド発行後に「OK(6)」リザルトが返ってくるかご確認願います。

**Comment by acs-tanakachikako** [comment]
使い方がよくわかってないですが、
コマンド発行後はプロンプトが返ってきません。Ctrl+CするとOK(6)が返ってきます。
エントリークラスでは位置が変わるようですが、プライマリクラスやアドバンストクラスでは変わらないようです。

**Comment by jtFuruhata** [comment]
追加情報ありがとうございます。これはetrobo環境ではなくβ版シミュレータのバグですので、ETロボコン参加者MLの方に問い合わせをお願いします。

**Comment by acs-tanakachikako** [comment]
承知しました。ありがとうございます。
