### ISSUE TITLE
動作環境構築手順（Mac）

### ISSUE THREAD

**Issue by jtFuruhata** [ETrobocon/etrobo#6]
etroboパッケージインストール前の動作環境構築手順（Mac）を整備する

**Comment by kuboaki** [comment]
そうそう、用意したほうがよいと思っていましたー！

2020年6月14日(日) 12:19 TANAHASHI, Jiro <notifications@github.com>:

**Comment by kuboaki** [comment]
asp を配られたとき、棚橋 make だと、コードからのビルドを試みて、中断してしまいます。

2020年6月14日(日) 14:06 Shin Kuboaki <kuboaki@cityfujisawa.ne.jp>:

**Comment by jtFuruhata** [comment]
これはつまり、ビルド済みのaspファイルをもらったのはいいけど、どこにいれて何のコマンドを叩けばいいかわからない、って感じですよね？

`$ETROBO_ROOT/ev3rt-athrill-v850e2m/sdk/workspace/` に置いて、`sim wait launch asp` なんですけど、 #8 立てました。確かにちょいとわからないっすね。

**Comment by kuboaki** [comment]
ご理解のとおりです。
ありがとうございます😊

2020年6月14日(日) 15:40 TANAHASHI, Jiro <notifications@github.com>:
