### ISSUE TITLE
ビルド済みAthrillアプリの操作

### ISSUE THREAD

**Issue by jtFuruhata** [ETrobocon/etrobo#8]
`hrp3/sdk/workspace`には`workspace`シンボリックリンクを貼り、実機への転送は`ev3`コマンドで便利になった。
でも、`ev3rt-athrill-v850e2m/sdk/workspace/`に生成されるasp/*.aspは完全に放置プレイで、いちいち掘るのが面倒

`ev3`コマンドと使用感を合わせて、`sim cp`とか`sim ls`とか作ってはどうか。

**Comment by kuboaki** [comment]
sim ッテコマンドはどこにありますか。

2020年6月14日(日) 14:35 TANAHASHI, Jiro <notifications@github.com>:

**Comment by jtFuruhata** [comment]
`sim`は`scripts`にありまっす。`scripts`にはパス通ってるので、どこにいても叩けます。

**Comment by jtFuruhata** [comment]
ビルドしたアプリは `simdist` フォルダへプロジェクトごとに格納され、 `sim launch <プロジェクト名>` で実行可能となっている。
