### ISSUE TITLE
各コマンドの詳細解説

### ISSUE THREAD

**Issue by jtFuruhata** [ETrobocon/etrobo#9]
コマンドリファレンスがない。ふふ。

**Comment by kuboaki** [comment]
ここでいいのか？

```
$ make sample03 sim up
invoker make sample03 sim up app=sample05
```

どうも、 `make sample03 sim up` としても、sample03 をビルドせず、
どっかでsample05をビルドしたことを覚えていて、app=sample05 をつけて実行してしまうようです。

make app=sample04 など、一度 app=を明示して実行ればよいのですが、
ちょっとこれ、気づきにくいです。

**Comment by jtFuruhata** [comment]
基本的にはmakeコマンドはEV3RT準拠ですので、そうなりますね。
また、残念ながらapp=/img=はちょっとmakeの仕組み的に省略できません。

**Comment by kuboaki** [comment]
ああ、いつもapp= をつけておけば、いいのですね。

2020年6月24日(水) 15:55 TANAHASHI, Jiro <notifications@github.com>:

**Comment by jtFuruhata** [comment]
ですです
